### PR TITLE
fix(exp_runner): correct task_id access path on EpisodeConfig

### PR DESCRIPTION
**Pull request by amanjaiswal73892**
## Summary
- Fixes `AttributeError: 'EpisodeConfig' object has no attribute 'task_id'` introduced in 0bbe3d71
- `EpisodeConfig` has no top-level `task_id` — the correct path is `episode.config.task_config.task_id`; fixed all four occurrences in `_run_sequentially_impl` and `_poll_ray`
- Adds a `test_run_sequentially` integration test so this regression is caught by CI going forward
- Adds `/// script` dependency block to `recipes/osworld/eval_azure_osworld.py`

## Test Plan
- [x] `pytest tests/test_experiment.py tests/test_episode.py` — 35 passed
- [x] New `test_run_sequentially` test exercises the exact code path that was broken

### CODE REVIEW

**Review by NicolasAG — APPROVED** [review]
Thanks for catching this!
